name: team2-main-notebook
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - seaborn
  - scipy
  - scikit-learn
  - pooch
  - jupyter
  - netcdf4
  - tqdm