name: 93463cac-471a-469d-ad52-0514fd9b67f2
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - jupyter
  - matplotlib
  - numpy
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - seaborn
  - scipy
  - scikit-learn
  - pooch
  - netcdf4
  - tqdm
